CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE ROLE audit_app LOGIN PASSWORD 'audit-test-only' NOSUPERUSER NOBYPASSRLS;
GRANT CONNECT, CREATE ON DATABASE audit_platform TO audit_app;
GRANT CREATE, USAGE ON SCHEMA public TO audit_app;
ALTER SCHEMA public OWNER TO audit_app;
GRANT USAGE ON TYPE vector TO audit_app;
